name: Continuous Deployment

on:
  push:
    branches:
      - main  # adjust this to your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Deploy to Google Cloud, for example to App Engine. You may need to adjust this
    # based on where you're deploying in GCP.
    - name: Deploy to GCP
      run: |
        gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJECT_ID }}