name: Deploy develop
on:
  push:
    branches:
    - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GKE_PROJECT }}
      run: |
        gcloud auth configure-docker us-east1-docker.pkg.dev
        docker build -t us-east1-docker.pkg.dev/$GOOGLE_PROJECT/latamimages/fastapi:latest .
        docker push us-east1-docker.pkg.dev/$GOOGLE_PROJECT/latamimages/fastapi:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f resources.yaml